trend_classes: 2
dropout: 0.85
fused_method: 'default'
backbone: 'stockchartnet'
attention_mode: 'sa'
gradlayer: 'layers[-3]'
embedding_dim: 128
kernel_size: 2
dropout_times: 1
ts_encoder:
  hidden_dim: 64
  num_layers: 2
  ts_embedding_dim: 160
  ctx_embedding_dim: 32
  embedding_dim: 128
  dropout: 0.1