trend_classes: 2
dropout: 0.8
backbone: 'stockchartnetv2'
attention_mode: 'simam'
gradlayer: 'layers[-2].project_conv[0]'
ts_encoder:
  hidden_dim: 64
  num_layers: 2
  ts_embedding_dim: 128
  ctx_embedding_dim: 32
  dropout: 0.1
  embedding_dim: 128