trend_classes: 2
dropout: 0.8
backbone: 'stockchartnet'
attention_mode: 'ca'
gradlayer: 'layers[-2].conv2'
ts_encoder:
  hidden_dim: 64
  num_layers: 2
  ts_embedding_dim: 128
  ctx_embedding_dim: 32
  dropout: 0.1
  embedding_dim: 1280