trend_classes: 2
dropout: 0.4
fused_method: 'concat'
backbone: 'stockchartnet'
attention_mode: 'ca'
gradlayer: 'layers[-3]'
embedding_dim: 128
kernel_size: 2
dropout_times: 4
ts_encoder:
  hidden_dim: 64
  num_layers: 2
  ts_embedding_dim: 160
  ctx_embedding_dim: 32
  embedding_dim: 128
  dropout: 0.1