trend_classes: 2
dropout: 0.6
fused_method: 'default'
backbone: 'stockchartnet'
attention_mode: 'ca'
gradlayer: 'layers[-3].conv2'
embedding_dim: 128
ts_encoder:
  hidden_dim: 64
  num_layers: 2
  ts_embedding_dim: 160
  ctx_embedding_dim: 32
  embedding_dim: 128
  dropout: 0.1