# config.yaml
# --- 数据参数 ---
data:
  cache: 'diskcache'
  db_path: "train_data/hist/"
  include_meta: false
  sampler: false
  train:
    stock_list_file: "train_stocks.txt"
    hist_data_file: 'fundamental_train.pkl'
  eval:
    stock_list_file: "eval_stocks.txt"
    hist_data_file: 'fundamental_eval.pkl'
  test:
    stock_list_file: "test_stocks.txt"
    hist_data_file: 'fundamental_test.pkl'
    #, 'ATR', 'OBV', 'CCI', 'ADX'
  features: ['open', 'high', 'low', 'close', 'volume', 'turn_over', 'MA5', 'MA10', 'MA20', 'RSI', 'MACD', 'ATR', 'OBV', 'CCI', 'ADX', 'vwap']
  temporal: ['month', 'day', 'weekday']
  numerical: ['pe_ttm', 'pb', 'ps_ttm', 'pcf_ncf_ttm']
  categorical: ['industry', 'code']

# --- 训练参数 ---
training:
  workers: 4
  finetune: false
  model: 'alstm-ae'
  awl: false
  clip_norm: 0
  losses: ['ts', 'ctx', 'pred', 'trend', 'return']
  loss_weights: [1, 1, 1, 1, 1]
  sequence_length: 50       # K线序列长度
  learning_rate: 0.00001
  min_learning_rate: 0.00001
  weight_decay: 0.00001
  warmup_epochs: 0
  batch_size: 1024
  num_epochs: 100
  kl_annealing_steps: 5
  kl_weight_initial: 0.0000
  kl_target: 0.00001
  kl_freebits: 5
  reset_heads: false
  tildeq: false
  model_save_path: "../fin_models/kline_encoder.pth"
  pretrained_path: "../fin_models/kline_pretrained.pth"
  processed_data_cache_path: "../fin_train_cache/"
  load_pretrained: true

# --- 设备配置 ---
device: "cuda"              # 如果有GPU则使用cuda，否则使用cpu
