# config.yaml
# --- 数据参数 ---
data:
  cache: 'diskcache'
  db_path: "train_data/hist/"
  include_meta: true
  train:
    stock_list_file: "train_stocks.txt"
    hist_data_file: 'fundamental_train.pkl'
  eval:
    stock_list_file: "eval_stocks.txt"
    hist_data_file: 'fundamental_eval.pkl'
  test:
    stock_list_file: "test_stocks.txt"
    hist_data_file: 'fundamental_test.pkl'
    #, 'ATR', 'OBV', 'CCI', 'ADX'
  features: ['open', 'high', 'low', 'close', 'volume', 'turn_over', 'MA5', 'MA10', 'MA20', 'RSI', 'MACD', 'ATR', 'OBV', 'CCI', 'ADX', 'vwap']
  numerical: ['pe_ttm', 'pb', 'ps_ttm', 'pcf_ncf_ttm']
  categorical: ['industry']

# --- 训练参数 ---
training:
  finetune: true
  model: 'lstm-ae'
  awl: false
  losses: ['ts', 'ctx', 'pred']
  loss_weights: [1., 0.2, 1]
  sequence_length: 50       # K线序列长度
  learning_rate: 0.0001
  min_learning_rate: 0.00001
  weight_decay: 0
  warmup_epochs: 0
  batch_size: 1024
  num_epochs: 200
  validation_split: 0.2     # 验证集比例
  model_save_path: "../fin_models/kline_encoder.pth"
  pretrained_path: "../fin_models/kline_pretrained.pth"
  processed_data_cache_path: "../fin_train_cache/"
  load_pretrained: false

# --- 设备配置 ---
device: "cuda"              # 如果有GPU则使用cuda，否则使用cpu
