# config.yaml
# --- 数据参数 ---
data:
  db_path: '../price_trend/cache'
  sampler: false
  encoder_path: '../hamuna_stock_data/train_data/hist/encoder.joblib'
  scaler_path: '../hamuna_stock_data/train_data/hist/scaler.joblib'
  train:
    stock_list_file: "../hamuna_stock_data/train_data/hist/train_stocks.txt"
    hist_data_file: '../hamuna_stock_data/train_data/hist/fundamental_train.pkl'
    img_caching_path: '../price_trend/train'
  eval:
    stock_list_file: "../hamuna_stock_data/train_data/hist/eval_stocks.txt"
    hist_data_file: '../hamuna_stock_data/train_data/hist/fundamental_eval.pkl'
    img_caching_path: '../price_trend/eval'
  finetune:
    stock_list_file: "../hamuna_stock_data/train_data/hist/finetune_stocks.txt"
    hist_data_file: '../hamuna_stock_data/train_data/hist/fundamental_finetune.pkl'
    img_caching_path: '../price_trend/finetune'
  test:
    stock_list_file: "../hamuna_stock_data/train_data/hist/test_stocks.txt"
    hist_data_file: '../hamuna_stock_data/train_data/hist/fundamental_test.pkl'
    img_caching_path: '../price_trend/test'
    #, 'ATR', 'OBV', 'CCI', 'ADX'
  features: ['open', 'high', 'low', 'close', 'MA20', 'turn_over']
  categorical: ['industry', 'code']
  ts_features:
    features: ['open', 'high', 'low', 'close', 'volume', 'turn_over', 'MA5', 'MA10', 'MA20', 'RSI', 'MACD', 'ATR', 'OBV', 'CCI', 'ADX', 'vwap']
    temporal: ['month', 'day', 'weekday']
    numerical: ['pe_ttm', 'pb', 'ps_ttm', 'pcf_ncf_ttm']
  sequence_length: 10       # K线序列长度
  image_size: 30

# --- 训练参数 ---
training:
  workers: 4
  finetune: true
  model: 'stocknet'
  awl: false
  clip_norm: 0
  optimizer: 'sgd'
  learning_rate: 0.0001
  min_learning_rate: 0.00001
  module_train: 'fusion'
  weight_decay: 0.05
  warmup_epochs: 0
  batch_size: 512
  num_epochs: 100
  model_save_path: "../fin_models/trend.pth"
  pretrained_path: "../fin_models/trend_pretrained.pth"
  finetune_path: "../fin_models/trend_finetune.pth"
  load_pretrained: false

# --- 设备配置 ---
device: "cuda"              # 如果有GPU则使用cuda，否则使用cpu
