# config.yaml
# --- 数据参数 ---
data:
  db_path: '../price_trend/cache'
  sampler: false
  encoder_path: '../hamuna_stock_data/train_data/hist/encoder.joblib'
  train:
    stock_list_file: "../hamuna_stock_data/train_data/hist/train_stocks.txt"
    hist_data_file: '../hamuna_stock_data/train_data/hist/fundamental_train.pkl'
    img_caching_path: '../price_trend/train'
  eval:
    stock_list_file: "../hamuna_stock_data/train_data/hist/eval_stocks.txt"
    hist_data_file: '../hamuna_stock_data/train_data/hist/fundamental_eval.pkl'
    img_caching_path: '../price_trend/eval'
  test:
    stock_list_file: "../hamuna_stock_data/train_data/hist/test_stocks.txt"
    hist_data_file: '../hamuna_stock_data/train_data/hist/fundamental_test.pkl'
    img_caching_path: '../price_trend/test'
    #, 'ATR', 'OBV', 'CCI', 'ADX'
  features: ['open', 'high', 'low', 'close', 'MA20', 'turn_over', 'volume']
  categorical: ['industry', 'code']
  sequence_length: 20       # K线序列长度
  image_size: 60

# --- 训练参数 ---
training:
  workers: 4
  finetune: false
  model: 'stocknet'
  awl: false
  clip_norm: 0
  losses: ['trend']
  loss_weights: [1]
  learning_rate: 0.01
  min_learning_rate: 0.00001
  weight_decay: 0.0001
  warmup_epochs: 0
  batch_size: 512
  num_epochs: 100
  model_save_path: "../fin_models/trend.pth"
  pretrained_path: "../fin_models/trend_pretrained.pth"
  load_pretrained: true

# --- 设备配置 ---
device: "cuda"              # 如果有GPU则使用cuda，否则使用cpu
