# config.yaml
# --- 数据参数 ---
data:
  cache: 'diskcache'
  db_path: "train_data/hist/"
  noise_level: 0.001
  noise_prob: 0.5
  ts_masking_ratio: 0.3
  include_meta: true
  train:
    stock_list_file: "train_stocks.txt"
    hist_data_file: 'fundamental_train.pkl'
  eval:
    stock_list_file: "eval_stocks.txt"
    hist_data_file: 'fundamental_eval.pkl'
  test:
    stock_list_file: "test_stocks.txt"
    hist_data_file: 'fundamental_test.pkl'
    #, 'ATR', 'OBV', 'CCI', 'ADX'
  features: ['open', 'high', 'low', 'close', 'volume', 'turn_over', 'MA5', 'MA10', 'MA20', 'RSI', 'MACD', 'ATR', 'OBV', 'CCI', 'ADX', 'vwap']
  numerical: ['pe_ttm', 'pb', 'ps_ttm', 'pcf_ncf_ttm']
  categorical: ['industry']

# --- 训练参数 ---
training:
  awl: true
  losses: ['ts', 'ctx', 'pred']
  loss_weights: [1., 1., 1.]
  sequence_length: 50       # K线序列长度
  ts_embedding_dim: 128         # 向量维度
  ctx_embedding_dim: 64         # 向量维度
  hidden_dim: 64           # LSTM隐藏层维度
  num_layers: 2             # LSTM层数
  predict_dim: 5            # 预测分支
  attention_dim: 64            # 预测分支
  learning_rate: 0.005
  min_learning_rate: 0.00001
  batch_size: 1024
  num_epochs: 200
  alpha: 0.2
  beta: 0.2
  dropout: 0.2
  validation_split: 0.2     # 验证集比例
  model_save_path: "../fin_models/kline_encoder.pth"
  pretrained_path: "../fin_models/kline_pretrained.pth"
  processed_data_cache_path: "../fin_train_cache/"
  load_pretrained: false

# --- 设备配置 ---
device: "cuda"              # 如果有GPU则使用cuda，否则使用cpu
