db:
  host: '10.26.0.8'
  port: '2000'
  username: 'hmcz'
  password: 'Hmcz_12345678'
embedding:
  device: "cuda"
  cache: 'diskcache'
  index_db: 'http://localhost:19531/default'
  collection_name: 'kline_embeddings'
  ann_field: 'embedding'
  metric_type: 'COSINE'  # Inner Product
  batch_size: 1024
  data:
    seq_len: 50
    scaler_path: '../hamuna_stock_data/train_data/hist/scaler.joblib'
    encoder_path: '../hamuna_stock_data/train_data/hist/encoder.joblib'
    features: ['open', 'high', 'low', 'close', 'volume', 'turn_over', 'MA5', 'MA10', 'MA20', 'RSI', 'MACD', 'ATR', 'OBV', 'CCI', 'ADX', 'vwap']
    numerical: ['pe_ttm', 'pb', 'ps_ttm', 'pcf_ncf_ttm']
    categorical: ['industry']
  model: 'lstm-ae'
  model_path: "../fin_models/kline_encoder.pth"

